spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    alicloud:
      access-key: access-key
      secret-key: secret-key
      oss:
        endpoint: endpoint
        bucket: bucket
      sms:
        host: host
        path: path
        skin: skin
        appcode: appcode
  application:
    name: gulimall-third-party
server:
  port: 8080
